### ISSUE TITLE
Парсер презентации

### ISSUE THREAD

**Issue by Bonoparte** [moevm/mse_public_speaking_training#4]
Создание модуля парсинга загруженной презентации для:
1) Послайдового вывода презентации
2) Возможности сопоставить текст на слайдах и распознанные слова, для возможности вычисления численного значения четкости речи (количество распознанных слов совпадающих с текстом на слайдах/общее количество слов на слайдах)

**Comment by AnastasiiaSmurova** [comment]
1. Подключение библиотеки python-pptx
2. Для получения списка слайдов используем функцию slides(), в результате получаем список слайдов.
3. Затем делаем словарь слайд - текст или наоборот)
Список слайдов у нас есть, проходим по нему и в для каждого слайда выполняем код:
**text_slide = " "
    for shape in slide.shapes:
       if not shape.has_text_frame:
          continue
       text_slide += shape.text_frame + "\n"**
И добавляем text_slide в словарь вместе с текстом
